### ISSUE TITLE
Offer

### ISSUE THREAD

**Issue by GarboMuffin** [Xeltalliv/forkphorus#1]
It seems you're much more interested in continuing development of forkphorus than I am. If you want, I'm willing to just give you write access to forkphorus/forkphorus.

Just going to leave that offer here. If you want to continue your own fork that's perfectly fine too.

**Comment by Xeltalliv** [comment]
Thanks for the offer, but I don't think that's a good idea.

This is actually my first time using node.js and typescript and I still haven't figured out how most parts of the forkphorus work. Having you review everything I do seems like a much safer option, so that I don't accidentally break something important or introduce a feature that you never intended forkphorus to have. Also I'm not even planning to do any long-term development on this fork. As for the current changes, I am planning to do pull requests with detailed explanations once I consider those branches done, which should hopefully happen soon.

Somewhat unrelated, but I would like to ask, are you interested in [new-webgl](https://github.com/Xeltalliv/forkphorus/tree/new-webgl) branch?

**Comment by GarboMuffin** [comment]
Sounds good. Just send them when you're ready.

I'm personally not going to spend time on improving the WebGL renderer, but if someone like you wants to, that's sounds great (definitely put that in a separate PR)
